//main action
export const PROBLEM_SOLVED = 'PROBLEM_SOLVED';
export const PROBLEM_NOT_SOLVED = 'PROBLEM_NOT_SOLVED';
export const PROBLEM_CREATED = 'PROBLEM_CREATED';
export const ANSWERS_CREATED = 'ANSWERS_CREATED';
export const SEED_INCREASED = 'SEED_INCREASED';
export const JOKE_FETCHED = 'JOKE_FETCHED';
export const REWARD_TOGGLED = 'REWARD_TOGGLED';
export const CAT_FACT_FETCHED = 'CAT_FACT_FETCHED';
export const SETTINGS_TOGGLED = 'SETTINGS_TOGGLED';
export const LEVEL_STEPS_CHANGED = 'LEVEL_STEPS_CHANGED';
export const REWARD_FREQUENCY_CHANGED = 'REWARD_FREQUENCY_CHANGED';
export const CAT_FACT_TOGGLED = 'CAT_FACT_TOGGLED';
export const DAD_JOKE_TOGGLED = 'DAD_JOKE_TOGGLED';
export const NEXT_REWARD_SET = 'NEXT_REWARD_SET';
export const ANSWER_INPUT_CHANGED = 'ANSWER_INPUT_CHANGED';
