//main action
export const PROBLEM_SOLVED = 'PROBLEM_SOLVED';
export const PROBLEM_NOT_SOLVED = 'PROBLEM_NOT_SOLVED';
export const PROBLEM_CREATED = 'PROBLEM_CREATED';
export const ANSWERS_CREATED = 'ANSWERS_CREATED';
export const SEED_INCREASED = 'SEED_INCREASED';
export const JOKE_FETCHED = 'JOKE_FETCHED';
export const SHOW_HIDE_JOKE = 'SHOW_HIDE_JOKE';
export const CAT_FACT_FETCHED = 'CAT_FACT_FETCHED';
