//main action
export const PROBLEM_SOLVED = 'PROBLEM_SOLVED';
export const PROBLEM_NOT_SOLVED = 'PROBLEM_NOT_SOLVED';
export const PROBLEM_CREATED = 'PROBLEM_CREATED';
export const ANSWERS_CREATED = 'ANSWERS_CREATED';
export const SEED_INCREASED = 'SEED_INCREASED';
// export const CREATE_SOLUTIONS = 'CREATE_SOLUTIONS';
// export const SELECT_OPERATION = 'SELECT_OPERATION';
